In [17]:
import tensorflow as tf
import numpy as np

## 创建张量

In [18]:
# 创建 0 维张量
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [19]:
# 创建 1 维张量
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [20]:
# 创建 2 维张量
tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
], dtype=tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [21]:
# 创建 3 维张量
tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=tf.float64)

<tf.Tensor: shape=(2, 2, 2), dtype=float64, numpy=
array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])>

## 转换成 numpy


In [ ]:
tensor1 = tf.constant([1,2,3])

np.array(tensor1)



array([1, 2, 3])

In [29]:
tensor1.numpy()

array([1, 2, 3])